[package]
name = "libbruteforce"
version = "1.0.0"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.11.1"
md5 = "0.7.0"
sha1 = "0.6.0"
sha2 = "0.8.1"
