# https://doc.rust-lang.org/cargo/reference/config.html

[build]
# Get maximum performance with all CPU features of the CPU that compiles this.
# See: https://stackoverflow.com/questions/65156743/what-target-features-uses-rustc-by-default
# I'm not sure if this affects crates that use this as library.
rustflags = [
    "-C",
    # without this, Rustc uses "fxsr,sse,sse2"
    "target-cpu=native"
]
